version: "3"
services:

  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}

    command: ["--config=/etc/otel/collector/agent_config.yaml"]
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
  ucs-splunk-o11y:

    build: ucs-api/.
    depends_on:
      - splunk-otel-collector


    command: >
      sh -c "python /app/runner.py"
    restart: always
